# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'fund_add_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AddFundDialog(object):
    def setupUi(self, AddFundDialog):
        AddFundDialog.setObjectName("AddFundDialog")
        AddFundDialog.resize(340, 169)
        self.gridLayout = QtWidgets.QGridLayout(AddFundDialog)
        self.gridLayout.setContentsMargins(-1, -1, -1, 9)
        self.gridLayout.setObjectName("gridLayout")
        self.cancelBtn = QtWidgets.QPushButton(AddFundDialog)
        self.cancelBtn.setFocusPolicy(QtCore.Qt.NoFocus)
        self.cancelBtn.setObjectName("cancelBtn")
        self.gridLayout.addWidget(self.cancelBtn, 2, 2, 1, 1)
        self.saveBtn = QtWidgets.QPushButton(AddFundDialog)
        self.saveBtn.setFocusPolicy(QtCore.Qt.TabFocus)
        self.saveBtn.setObjectName("saveBtn")
        self.gridLayout.addWidget(self.saveBtn, 2, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 2, 0, 1, 1)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setVerticalSpacing(15)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.Label = QtWidgets.QLabel(AddFundDialog)
        self.Label.setObjectName("Label")
        self.gridLayout_2.addWidget(self.Label, 0, 0, 1, 1)
        self.fundCode = QtWidgets.QLineEdit(AddFundDialog)
        self.fundCode.setClearButtonEnabled(True)
        self.fundCode.setObjectName("fundCode")
        self.gridLayout_2.addWidget(self.fundCode, 0, 1, 1, 1)
        self.Label_2 = QtWidgets.QLabel(AddFundDialog)
        self.Label_2.setObjectName("Label_2")
        self.gridLayout_2.addWidget(self.Label_2, 1, 0, 1, 1)
        self.fundCost = QtWidgets.QLineEdit(AddFundDialog)
        self.fundCost.setClearButtonEnabled(True)
        self.fundCost.setObjectName("fundCost")
        self.gridLayout_2.addWidget(self.fundCost, 1, 1, 1, 1)
        self.Label_3 = QtWidgets.QLabel(AddFundDialog)
        self.Label_3.setObjectName("Label_3")
        self.gridLayout_2.addWidget(self.Label_3, 2, 0, 1, 1)
        self.fundUnits = QtWidgets.QLineEdit(AddFundDialog)
        self.fundUnits.setClearButtonEnabled(True)
        self.fundUnits.setObjectName("fundUnits")
        self.gridLayout_2.addWidget(self.fundUnits, 2, 1, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_2, 0, 0, 1, 3)

        self.retranslateUi(AddFundDialog)
        self.saveBtn.clicked.connect(AddFundDialog.accept)
        self.cancelBtn.clicked.connect(AddFundDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(AddFundDialog)
        AddFundDialog.setTabOrder(self.fundCode, self.fundCost)
        AddFundDialog.setTabOrder(self.fundCost, self.fundUnits)
        AddFundDialog.setTabOrder(self.fundUnits, self.saveBtn)
        AddFundDialog.setTabOrder(self.saveBtn, self.cancelBtn)

    def retranslateUi(self, AddFundDialog):
        _translate = QtCore.QCoreApplication.translate
        AddFundDialog.setWindowTitle(_translate("AddFundDialog", "Dialog"))
        self.cancelBtn.setText(_translate("AddFundDialog", "取消"))
        self.saveBtn.setText(_translate("AddFundDialog", "保存"))
        self.saveBtn.setShortcut(_translate("AddFundDialog", "Return"))
        self.Label.setText(_translate("AddFundDialog", "基金代码"))
        self.fundCode.setPlaceholderText(_translate("AddFundDialog", "基金代码或名称"))
        self.Label_2.setText(_translate("AddFundDialog", "持仓成本"))
        self.fundCost.setPlaceholderText(_translate("AddFundDialog", "基金持仓成本价"))
        self.Label_3.setText(_translate("AddFundDialog", "持有份额"))
        self.fundUnits.setPlaceholderText(_translate("AddFundDialog", "基金持有份额"))
