# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'fundChartDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_FundChartDialog(object):
    def setupUi(self, FundChartDialog):
        FundChartDialog.setObjectName("FundChartDialog")
        FundChartDialog.resize(609, 344)
        self.gridLayout = QtWidgets.QGridLayout(FundChartDialog)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.chartLayout = QtWidgets.QGridLayout()
        self.chartLayout.setObjectName("chartLayout")
        self.gridLayout.addLayout(self.chartLayout, 0, 0, 1, 1)

        self.retranslateUi(FundChartDialog)
        QtCore.QMetaObject.connectSlotsByName(FundChartDialog)

    def retranslateUi(self, FundChartDialog):
        _translate = QtCore.QCoreApplication.translate
        FundChartDialog.setWindowTitle(_translate("FundChartDialog", "Dialog"))
