# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'fund_update_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_FundUpdateDialog(object):
    def setupUi(self, FundUpdateDialog):
        FundUpdateDialog.setObjectName("FundUpdateDialog")
        FundUpdateDialog.resize(381, 190)
        self.gridLayout = QtWidgets.QGridLayout(FundUpdateDialog)
        self.gridLayout.setObjectName("gridLayout")
        self.update_now_btn = QtWidgets.QPushButton(FundUpdateDialog)
        self.update_now_btn.setObjectName("update_now_btn")
        self.gridLayout.addWidget(self.update_now_btn, 4, 3, 1, 1)
        self.next_time_btn = QtWidgets.QPushButton(FundUpdateDialog)
        self.next_time_btn.setObjectName("next_time_btn")
        self.gridLayout.addWidget(self.next_time_btn, 4, 4, 1, 1)
        self.chang_log_brower = QtWidgets.QTextBrowser(FundUpdateDialog)
        self.chang_log_brower.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.chang_log_brower.setOpenExternalLinks(True)
        self.chang_log_brower.setObjectName("chang_log_brower")
        self.gridLayout.addWidget(self.chang_log_brower, 3, 0, 1, 5)
        self.label_3 = QtWidgets.QLabel(FundUpdateDialog)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 3)
        self.version_info_txt = QtWidgets.QLabel(FundUpdateDialog)
        self.version_info_txt.setObjectName("version_info_txt")
        self.gridLayout.addWidget(self.version_info_txt, 1, 0, 1, 5)
        self.label_4 = QtWidgets.QLabel(FundUpdateDialog)
        self.label_4.setMinimumSize(QtCore.QSize(28, 28))
        self.label_4.setMaximumSize(QtCore.QSize(28, 16777215))
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap(":/icon/info/info.png"))
        self.label_4.setScaledContents(True)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 0, 0, 1, 1)
        self.label = QtWidgets.QLabel(FundUpdateDialog)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 1, 1, 3)
        self.update_process_bar = QtWidgets.QProgressBar(FundUpdateDialog)
        self.update_process_bar.setMinimumSize(QtCore.QSize(180, 0))
        self.update_process_bar.setMaximumSize(QtCore.QSize(16777215, 20))
        self.update_process_bar.setProperty("value", 24)
        self.update_process_bar.setObjectName("update_process_bar")
        self.gridLayout.addWidget(self.update_process_bar, 4, 0, 1, 3)

        self.retranslateUi(FundUpdateDialog)
        QtCore.QMetaObject.connectSlotsByName(FundUpdateDialog)

    def retranslateUi(self, FundUpdateDialog):
        _translate = QtCore.QCoreApplication.translate
        FundUpdateDialog.setWindowTitle(_translate("FundUpdateDialog", "Dialog"))
        self.update_now_btn.setText(_translate("FundUpdateDialog", "立即升级"))
        self.next_time_btn.setText(_translate("FundUpdateDialog", "下次再说"))
        self.label_3.setText(_translate("FundUpdateDialog", "更新日志："))
        self.version_info_txt.setText(_translate("FundUpdateDialog", "当前版本：1.4.0，最新版本：1.5.0，发布日期：2021年1月26日 "))
        self.label.setText(_translate("FundUpdateDialog", "韭菜盒子有新版本了！是否立即更新？"))
import ui.fundViewResource_rc
