# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'fundImageDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_FundImageDialog(object):
    def setupUi(self, FundImageDialog):
        FundImageDialog.setObjectName("FundImageDialog")
        FundImageDialog.resize(480, 267)
        self.gridLayout = QtWidgets.QGridLayout(FundImageDialog)
        self.gridLayout.setContentsMargins(10, 10, 10, 10)
        self.gridLayout.setObjectName("gridLayout")
        self.imageLabel = QtWidgets.QLabel(FundImageDialog)
        self.imageLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.imageLabel.setObjectName("imageLabel")
        self.gridLayout.addWidget(self.imageLabel, 0, 0, 1, 1)

        self.retranslateUi(FundImageDialog)
        QtCore.QMetaObject.connectSlotsByName(FundImageDialog)

    def retranslateUi(self, FundImageDialog):
        _translate = QtCore.QCoreApplication.translate
        FundImageDialog.setWindowTitle(_translate("FundImageDialog", "Dialog"))
        self.imageLabel.setText(_translate("FundImageDialog", "此处为图片"))
