# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'fundChartDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_FundChartDialog(object):
    def setupUi(self, FundChartDialog):
        FundChartDialog.setObjectName("FundChartDialog")
        FundChartDialog.resize(609, 344)
        self.gridLayout = QtWidgets.QGridLayout(FundChartDialog)
        self.gridLayout.setContentsMargins(0, 0, 0, 15)
        self.gridLayout.setObjectName("gridLayout")
        self.oneMonthRadio = QtWidgets.QRadioButton(FundChartDialog)
        self.oneMonthRadio.setObjectName("oneMonthRadio")
        self.gridLayout.addWidget(self.oneMonthRadio, 1, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 1, 6, 1, 1)
        self.chartLayout = QtWidgets.QGridLayout()
        self.chartLayout.setContentsMargins(-1, -1, -1, 0)
        self.chartLayout.setObjectName("chartLayout")
        self.gridLayout.addLayout(self.chartLayout, 0, 0, 1, 7)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 1, 0, 1, 1)
        self.threeYearRadio = QtWidgets.QRadioButton(FundChartDialog)
        self.threeYearRadio.setObjectName("threeYearRadio")
        self.gridLayout.addWidget(self.threeYearRadio, 1, 5, 1, 1)
        self.threeMonthRadio = QtWidgets.QRadioButton(FundChartDialog)
        self.threeMonthRadio.setChecked(True)
        self.threeMonthRadio.setObjectName("threeMonthRadio")
        self.gridLayout.addWidget(self.threeMonthRadio, 1, 2, 1, 1)
        self.sixMonthRadio = QtWidgets.QRadioButton(FundChartDialog)
        self.sixMonthRadio.setObjectName("sixMonthRadio")
        self.gridLayout.addWidget(self.sixMonthRadio, 1, 3, 1, 1)
        self.oneYearRadio = QtWidgets.QRadioButton(FundChartDialog)
        self.oneYearRadio.setObjectName("oneYearRadio")
        self.gridLayout.addWidget(self.oneYearRadio, 1, 4, 1, 1)

        self.retranslateUi(FundChartDialog)
        QtCore.QMetaObject.connectSlotsByName(FundChartDialog)

    def retranslateUi(self, FundChartDialog):
        _translate = QtCore.QCoreApplication.translate
        FundChartDialog.setWindowTitle(_translate("FundChartDialog", "Dialog"))
        self.oneMonthRadio.setText(_translate("FundChartDialog", "近1月"))
        self.threeYearRadio.setText(_translate("FundChartDialog", "近3年"))
        self.threeMonthRadio.setText(_translate("FundChartDialog", "近3月"))
        self.sixMonthRadio.setText(_translate("FundChartDialog", "近6月"))
        self.oneYearRadio.setText(_translate("FundChartDialog", "近1年"))
